# Site
repository: kangmin46/resume
# favicon: images/favicon.ico

# Personal info
name: 김강민
title: 백엔드 엔지니어 지망생
email: kangminals5610@gmail.com

# Social links
github_username: kangmin46
# dribbble_username: jekyll
# facebook_username: devbeginner
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/김강민.jpg
about_content: | # this will include new lines to allow paragraphs
  Java, Spring, 객체지향 설계, 클린 코드 등에 관심이 많은 개발자입니다. 
  
  개발을 하면서 백엔드에서의 성능 향상을 고민하던 중 데이터베이스 설계, 쿼리 튜닝 등에 관심이 생겨 스터디를 조직해 데이터베이스를 학습하고 있습니다.  
  
  기능을 단순히 구현하는 것이 아닌, 안정적이고 생산적으로 개발하기 위해 고민하는 성향을 가졌습니다. 
  
  원하는 서비스를 별 다른 문제 없이, 바르게 개발할 수 있는 사람으로 성장하고 싶습니다.  
  
  팀 프로젝트를 통해서 유기적인 소통과 좋은 팀 문화가 좋은 결과물을 산출해 낸다는 사실을 직접 경험했습니다.
  
  이러한 경험을 바탕으로 좋은 개발 문화에 관심을 가지게 되었습니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
